/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.forecast.server;

import org.junit.Test;
import static org.junit.Assert.*;

public class ServerTest {
    @Test
    public void appHasAGreeting() {
        Server classUnderTest = new Server();
        assertNotNull("server should have a logger", classUnderTest.getLogger());
    }
}
